# Generated by Django 4.2.17 on 2025-05-14 08:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="%(class)s_groups",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="%(class)s_user_permissions",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "swappable": "AUTH_USER_MODEL",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        choices=[
                            ("categories/sport/index.html", "Спорт"),
                            ("categories/tech/index.html", "Техника"),
                            ("categories/home/index.html", "Дом и сад"),
                            ("categories/clothes/index.html", "Одежда и обувь"),
                            ("categories/books/index.html", "Книги"),
                            ("categories/cars/index.html", "Авто"),
                        ],
                        default="categories/tech/index.html",
                        verbose_name="Here is the choose category for publication.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "db_table": "categories",
            },
        ),
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title is unique and must have a length before 100 symbols.\n Min length is the 3 symbols.",
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.MaxLengthValidator(
                                limit_value=100,
                                message="Max length (of title) 100 symbols",
                            ),
                            django.core.validators.MinLengthValidator(
                                limit_value=3, message="Min length (of title) 3 symbols"
                            ),
                            django.core.validators.RegexValidator(
                                message="The title not have correct format.",
                                regex="^(?!.*  )[a-zA-Zа-яА-ЯёЁ][\\w \\-_\\dа-яА-ЯёЁ]{1,48}[a-zA-Zа-яА-ЯёЁ]$[^\\S\\W \\\\]?",
                            ),
                        ],
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description for the ad",
                        max_length=500,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                limit_value=10, message="Min length is the 10 symbols"
                            ),
                            django.core.validators.MaxLengthValidator(
                                limit_value=50, message="Max length 500 symbols"
                            ),
                        ],
                        verbose_name="Description",
                    ),
                ),
                (
                    "image_url",
                    models.CharField(
                        help_text="The path to the image",
                        max_length=100,
                        validators=[
                            django.core.validators.MaxLengthValidator(
                                limit_value=100,
                                message="Max length (of path) 100 symbols",
                            ),
                            django.core.validators.MinLengthValidator(
                                limit_value=1, message="Min length (of path) 1 symbols"
                            ),
                            django.core.validators.RegexValidator(
                                message="The path has the invalid format",
                                regex="(\\/||^(?!.*  )[a-z][\\w\\-_\\d]{1,9}\\/$[^\\S\\W ])",
                            ),
                        ],
                        verbose_name="path",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "condition",
                    models.BooleanField(
                        default=False,
                        help_text="Default is False (not activated), if you want the public page it means that True",
                        verbose_name="Activated",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="ads.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ad",
                "verbose_name_plural": "Ads",
                "db_table": "ads",
            },
        ),
    ]
