# Generated by Django 4.2.17 on 2025-05-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_customuser_ad_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        choices=[
                            ("categories/sport/index.html", "Спорт"),
                            ("categories/tech/index.html", "Техника"),
                            ("categories/home/index.html", "Дом и сад"),
                            ("categories/clothes/index.html", "Одежда и обувь"),
                            ("categories/books/index.html", "Книги"),
                            ("categories/cars/index.html", "Авто"),
                        ],
                        default="categories/tech/index.html",
                        verbose_name="Here is the choose category for publication.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Path",
                "verbose_name_plural": "Paths",
                "db_table": "paths",
            },
        ),
        migrations.RemoveField(
            model_name="ad",
            name="category",
        ),
        migrations.RemoveField(
            model_name="category",
            name="path",
        ),
    ]
