# Generated by Django 4.2.17 on 2025-05-14 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0003_categorypath_remove_ad_category_remove_category_path"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        help_text="Text of the comment. Min. 150 and Max. 1200. ",
                        max_length=1200,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                150, "Min length of comment is the 150 symbols"
                            ),
                            django.core.validators.MaxLengthValidator(
                                1200, "Max length of comment is the 1200 symbols"
                            ),
                            django.core.validators.RegexValidator(
                                message="The text not have correct format.",
                                regex="^(?!.*  )[a-zA-Zа-яА-ЯёЁ][\\w \\-_\\dа-яА-ЯёЁ]{1,}[^\\S\\W \\\\]?",
                            ),
                        ],
                        verbose_name="Comment",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        auto_now_add=True, help_text="Date when the comment was created"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACCEPTED", "Принял"),
                            ("DECLINED", "Отклонен"),
                            ("WATING", "Ожидает"),
                        ],
                        default="WATING",
                        help_text="Status for the exchange",
                        verbose_name="Status",
                    ),
                ),
                (
                    "ad_sender",
                    models.IntegerField(
                        blank=True,
                        help_text="This the index of sender",
                        null=True,
                        verbose_name="Sender",
                    ),
                ),
                (
                    "ad_receiver",
                    models.IntegerField(
                        blank=True,
                        help_text="This the index of receiver",
                        null=True,
                        verbose_name="Receiver",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="CategoryPath",
        ),
        migrations.AddField(
            model_name="ad",
            name="category",
            field=models.CharField(
                choices=[
                    ("NEW", "Новое"),
                    ("USED", "Использованное"),
                    ("UNKNOWN", "Неизвестно"),
                ],
                default="UNKNOWN",
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="category_path",
            field=models.CharField(
                choices=[
                    ("categories/sport/index.html", "Спорт"),
                    ("categories/tech/index.html", "Техника"),
                    ("categories/home/index.html", "Дом и сад"),
                    ("categories/clothes/index.html", "Одежда и обувь"),
                    ("categories/books/index.html", "Книги"),
                    ("categories/cars/index.html", "Авто"),
                ],
                default="('categories/clothes/index.html', 'Одежда и обувь')",
                help_text="pathname",
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="path",
            field=models.CharField(
                choices=[
                    ("categories/sport/index.html", "Спорт"),
                    ("categories/tech/index.html", "Техника"),
                    ("categories/home/index.html", "Дом и сад"),
                    ("categories/clothes/index.html", "Одежда и обувь"),
                    ("categories/books/index.html", "Книги"),
                    ("categories/cars/index.html", "Авто"),
                ],
                default="categories/tech/index.html",
                verbose_name="Here is the choose category for publication.",
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="status",
            field=models.BooleanField(
                default=False,
                help_text="Default is False (not activated), if you want the public page it means that True",
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="created_at",
            field=models.DateField(
                auto_now_add=True,
                help_text="Date when the ad was created",
                verbose_name="Created at",
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="user",
            field=models.IntegerField(
                blank=True,
                help_text="This is Index from the publisher of the ad",
                null=True,
                verbose_name="Publisher",
            ),
        ),
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
