# Generated by Django 4.2.17 on 2025-05-15 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ads", "0005_alter_exchangeproposal_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exchangeproposal",
            options={
                "verbose_name": "Exchange Proposal",
                "verbose_name_plural": "Exchange Proposals",
            },
        ),
        migrations.RemoveField(
            model_name="exchangeproposal",
            name="ad_receiver",
        ),
        migrations.RemoveField(
            model_name="exchangeproposal",
            name="ad_sender",
        ),
        migrations.RemoveField(
            model_name="exchangeproposal",
            name="status",
        ),
        migrations.CreateModel(
            name="Exchange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACCEPTED", "Принял"),
                            ("DECLINED", "Отклонен"),
                            ("WAITING", "Ожидает"),
                            ("READED", "Прочитано"),
                        ],
                        default="WAITING",
                        help_text="Status for the exchange",
                        verbose_name="Status",
                    ),
                ),
                (
                    "ad_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ad",
                        to="ads.ad",
                    ),
                ),
                (
                    "ad_receiver",
                    models.ForeignKey(
                        blank=True,
                        help_text="This the index of receiver",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ad_receiver",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Receiver",
                    ),
                ),
                (
                    "ad_sender",
                    models.ForeignKey(
                        blank=True,
                        help_text="This the index of sender",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ad_sender",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Sender",
                    ),
                ),
                (
                    "comment_id",
                    models.ForeignKey(
                        blank=True,
                        help_text="This the index of comment (Exchange proposal)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comment_id",
                        to="ads.exchangeproposal",
                        verbose_name="Proposal",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exchange",
                "verbose_name_plural": "Exchanges",
            },
        ),
    ]
