# Generated by Django 4.2.17 on 2025-05-15 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ads", "0006_alter_exchangeproposal_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="user",
            field=models.ForeignKey(
                help_text="This the index of sender",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Sender",
            ),
        ),
        migrations.CreateModel(
            name="ImageStorage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_name",
                    models.CharField(max_length=100, verbose_name="File name"),
                ),
                ("size", models.PositiveIntegerField(verbose_name="File weight")),
                (
                    "upload_date",
                    models.DateField(auto_now_add=True, verbose_name="Date upload"),
                ),
                (
                    "file_path",
                    models.ImageField(
                        help_text="Upload image/files. Pathname has a template format is: 'media/<user_pk>/%Y/%m/%d/' ",
                        upload_to="media/uploads/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Path to image",
                "verbose_name_plural": "Paths to images",
                "db_table": "image_storage",
            },
        ),
        migrations.CreateModel(
            name="FileAd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ad_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ads.ad",
                    ),
                ),
                (
                    "file_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ads.imagestorage",
                        verbose_name="Image upload path",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="exchange",
            name="file_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ads.imagestorage",
                verbose_name="Image upload path",
            ),
        ),
    ]
