# Generated by Django 4.2.17 on 2025-05-16 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ads", "0007_alter_ad_user_imagestorage_filead_exchange_file_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="This the index of sender",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Sender",
            ),
        ),
    ]
