# Generated by Django 4.2.17 on 2025-05-16 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0008_alter_ad_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="image_url",
            field=models.CharField(
                blank=True,
                help_text="The path to the image",
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.MaxLengthValidator(
                        limit_value=100, message="Max length (of path) 100 symbols"
                    ),
                    django.core.validators.MinLengthValidator(
                        limit_value=1, message="Min length (of path) 1 symbols"
                    ),
                    django.core.validators.RegexValidator(
                        message="The path has the invalid format",
                        regex="(\\/||^(?!.*  )[a-z][\\w\\-_\\d]{1,9}\\/$[^\\S\\W ])",
                    ),
                ],
                verbose_name="path",
            ),
        ),
    ]
