# Generated by Django 4.2.17 on 2025-05-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0009_alter_ad_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="condition",
            field=models.CharField(
                choices=[
                    ("ACTIVATED", "Опубликовано"),
                    ("DEACTIVATED", "Не опубликовано"),
                ],
                default="Не опубликовано",
                help_text="By default is state 'Не опубликовано, if you want to public your ad choose  'Опубликовано'. This means what your ad wil be public.",
                verbose_name="Activated",
            ),
        ),
    ]
