# Generated by Django 4.2.17 on 2025-05-16 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0011_alter_imagestorage_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imagestorage",
            name="original_name",
        ),
    ]
