# Generated by Django 4.2.17 on 2025-05-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0012_remove_imagestorage_original_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagestorage",
            name="file_path",
            field=models.FileField(
                help_text="Upload image/files. Pathname has a template format is: 'media/<user_pk>/%Y/%m/%d/' ",
                upload_to="media/uploads/",
                verbose_name="Image",
            ),
        ),
    ]
