# Generated by Django 4.2.17 on 2025-05-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0013_alter_imagestorage_file_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagestorage",
            name="id",
            field=models.IntegerField(
                primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
