# Generated by Django 4.2.17 on 2025-05-18 01:55

import ads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0014_alter_imagestorage_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagestorage",
            name="file_path",
            field=models.FileField(
                help_text="Upload image/files. Pathname has a template format is: 'media/<user_pk>/%Y/%m/%d/' ",
                upload_to=ads.models.receive_image_path,
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="imagestorage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
