# Generated by Django 4.2.17 on 2025-05-21 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0015_alter_imagestorage_file_path_alter_imagestorage_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ad",
            options={
                "permissions": [
                    ("can_publish", "Can publish"),
                    ("can_edit", "Can edit"),
                    ("can_delete", "Can delete"),
                    ("can_view", "Can view"),
                ],
                "verbose_name": "Ad",
                "verbose_name_plural": "Ads",
            },
        ),
        migrations.AlterModelOptions(
            name="exchangeproposal",
            options={
                "permissions": [
                    ("can_publish", "Can publish"),
                    ("can_edit", "Can edit"),
                    ("can_delete", "Can delete"),
                    ("can_view", "Can view"),
                ],
                "verbose_name": "Exchange Proposal",
                "verbose_name_plural": "Exchange Proposals",
            },
        ),
        migrations.AlterModelOptions(
            name="imagestorage",
            options={
                "permissions": [
                    ("can_publish", "Can publish"),
                    ("can_delete", "Can delete"),
                    ("can_view", "Can view"),
                ],
                "verbose_name": "Path to image",
                "verbose_name_plural": "Paths to images",
            },
        ),
    ]
