# Generated by Django 4.2.17 on 2025-06-19 03:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0017_alter_ad_options_alter_exchangeproposal_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="title",
            field=models.CharField(
                help_text="The title is unique and must have a length before 100 symbols.\n Min length is the 3 symbols.",
                max_length=100,
                unique=True,
                validators=[
                    django.core.validators.MaxLengthValidator(
                        limit_value=100, message="Max length (of title) 100 symbols"
                    ),
                    django.core.validators.MinLengthValidator(
                        limit_value=3, message="Min length (of title) 3 symbols"
                    ),
                    django.core.validators.RegexValidator(
                        message="The title not have correct format.",
                        regex="^(?!.*  )[a-zA-Zа-яА-ЯёЁ][\\w ,\\-_\\dа-яА-ЯёЁ]{1,98}[a-zA-Zа-яА-ЯёЁ]$[^\\S\\W \\\\]?",
                    ),
                ],
                verbose_name="Title",
            ),
        ),
    ]
