# Generated by Django 4.2.17 on 2025-06-19 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ads", "0018_alter_ad_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="user",
            field=models.ForeignKey(
                help_text="This the index of sender",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Sender",
            ),
        ),
    ]
