# Generated by Django 4.2.17 on 2025-06-22 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0019_alter_ad_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ad",
            options={
                "permissions": [
                    ("author_can_publish", "Can own publish"),
                    ("author_can_edit", "Can own edit"),
                    ("author_can_delete", "Can own delete"),
                    ("author_can_view", "Can own view"),
                ],
                "verbose_name": "Ad",
                "verbose_name_plural": "Ads",
            },
        ),
    ]
